import {
  BarChart3,
  BellRing,
  CalendarClock,
  Clock,
  Filter,
  Image as ImageIcon,
  Languages,
  Layers,
  MapPin,
  MessageSquareHeart,
  Palette,
  QrCode,
  Repeat,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Wand2,
} from "lucide-react";
import aiPostsImg from "@/assets/feature-ai-posts.jpg";
import schedulingImg from "@/assets/feature-scheduling.jpg";
import reviewsImg from "@/assets/review-management-dashboard.png.asset.json";
import magicQrImg from "@/assets/feature-magic-qr.jpg";
import type { FeaturePageConfig } from "./feature-page";

export const aiPostGeneration: FeaturePageConfig = {
  slug: "/features/ai-post-generation",
  eyebrow: "AI Post Generation",
  title: "AI Post Generation",
  headline: "Write a month of Google posts in minutes.",
  subtitle:
    "Vizogen studies your business type, services and location, then writes ready-to-publish Google Business Profile posts with local keywords, a clear offer and a matching image — in your brand voice.",
  image: aiPostsImg,
  imageAlt: "Vizogen AI post generator creating a Google Business Profile update",
  heroBadge: { value: "30 posts", label: "generated in one session" },
  stats: [
    { value: "10 sec", label: "Average time per post" },
    { value: "12+", label: "Languages supported" },
    { value: "3x", label: "More profile activity" },
  ],
  how: [
    { n: "01", title: "Connect your profile", desc: "Link your Google Business Profile once — Vizogen imports your categories, services and service area." },
    { n: "02", title: "Describe the update", desc: "Type an offer, news or seasonal idea in one line. Or pick a suggested topic from the AI content planner." },
    { n: "03", title: "Generate & preview", desc: "AI writes the caption, hashtags, CTA button and picks a visual. See a live Google preview before you commit." },
    { n: "04", title: "Publish or queue", desc: "Post instantly or push it into your schedule so your profile keeps getting fresh content weekly." },
  ],
  capabilities: [
    { icon: Wand2, title: "Brand voice control", desc: "Choose friendly, professional, festive or promotional tone — output stays consistent across every post." },
    { icon: ImageIcon, title: "Matching visuals", desc: "Get AI image suggestions or upload your own; Vizogen crops them to Google's recommended ratio." },
    { icon: MapPin, title: "Local keyword injection", desc: "Posts include city and service keywords that help you show up in nearby searches." },
    { icon: Languages, title: "Multi-language output", desc: "Publish in English, Hindi, Marathi, Tamil and more — great for multi-region businesses." },
    { icon: Layers, title: "Bulk generation", desc: "Create a full month of content in one pass and edit anything before it goes live." },
    { icon: Sparkles, title: "Offer & event posts", desc: "Switch post type between update, offer, event or product with the right fields auto-filled." },
  ],
  without: [
    "Staring at a blank caption box every week",
    "Recycling the same three photos",
    "Forgetting to mention your city or service",
    "Copy that reads generic and off-brand",
    "Hours lost writing instead of serving customers",
    "Profile goes quiet for weeks at a time",
  ],
  withVizogen: [
    "AI drafts a first version in seconds",
    "Fresh visual suggested for every post",
    "Local keywords included automatically",
    "Consistent tone across the whole calendar",
    "A month of content built in one sitting",
    "Profile stays active and ranking-friendly",
  ],
  faqs: [
    { q: "Do I have to publish exactly what the AI writes?", a: "No. Every draft is fully editable — change the text, swap the image or regenerate with a different tone before publishing." },
    { q: "Will Google penalise AI-written posts?", a: "Google cares about helpfulness, not authorship. Vizogen writes specific, business-accurate copy about your real services and offers." },
    { q: "Can it write for multiple locations?", a: "Yes. Each connected location gets its own city, services and voice, so posts never read like copy-paste duplicates." },
    { q: "Can I reuse a post that performed well?", a: "Yes — duplicate any published post, let AI rewrite it with a fresh angle, and re-queue it." },
  ],
  ctaHeading: "Never write a Google post from scratch again.",
  ctaText: "Start a free demo and watch Vizogen generate a week of on-brand posts for your business in under two minutes.",
};

export const smartScheduling: FeaturePageConfig = {
  slug: "/features/smart-scheduling",
  eyebrow: "Smart Scheduling",
  title: "Smart Scheduling",
  headline: "Post at the hours your customers actually search.",
  subtitle:
    "Build a content calendar once and let Vizogen publish it for you. Smart Scheduling picks peak local hours, spaces posts out evenly and keeps your Google Business Profile active even on your busiest weeks.",
  image: schedulingImg,
  imageAlt: "Vizogen scheduling calendar with queued Google Business Profile posts",
  heroBadge: { value: "20+ hrs", label: "saved every month" },
  stats: [
    { value: "365", label: "Days of hands-off posting" },
    { value: "0", label: "Missed publish windows" },
    { value: "4x", label: "More consistent activity" },
  ],
  how: [
    { n: "01", title: "Pick a cadence", desc: "Daily, three times a week or weekly — set how often each location should publish." },
    { n: "02", title: "Fill the queue", desc: "Drop AI-generated or manual posts into the calendar. Drag to reorder anything." },
    { n: "03", title: "Let AI pick the time", desc: "Vizogen suggests the highest-intent slots based on local search and engagement patterns." },
    { n: "04", title: "Track and adjust", desc: "See what published, what's pending and which slots earn the most views, then refine." },
  ],
  capabilities: [
    { icon: CalendarClock, title: "Visual calendar", desc: "Week and month views with drag-and-drop rescheduling for every connected location." },
    { icon: Clock, title: "Best-time suggestions", desc: "AI recommends publish windows instead of dumping posts at random hours." },
    { icon: Repeat, title: "Recurring campaigns", desc: "Set weekly specials or seasonal offers to repeat automatically until you pause them." },
    { icon: BellRing, title: "Failure alerts", desc: "If Google rejects or delays a post, you get notified with a one-tap retry." },
    { icon: Layers, title: "Multi-location queues", desc: "Schedule once and stagger publishing across branches so each profile stays unique." },
    { icon: BarChart3, title: "Slot performance", desc: "Compare views by day and hour to double down on the windows that convert." },
  ],
  without: [
    "Phone reminders you keep snoozing",
    "Posting late at night when nobody searches",
    "Weeks with five posts, then a month with none",
    "No plan for festivals or seasonal peaks",
    "Every branch handled manually",
    "No idea which timing worked",
  ],
  withVizogen: [
    "Queue runs itself in the background",
    "AI-picked peak local publish times",
    "Even, consistent cadence all year",
    "Seasonal campaigns planned in advance",
    "All locations scheduled from one screen",
    "Timing insights from real performance data",
  ],
  faqs: [
    { q: "What happens if I want to pause everything?", a: "Pause the queue with one toggle — scheduled posts hold their slots until you resume." },
    { q: "Can I approve posts before they publish?", a: "Yes. Turn on approval mode and nothing leaves the queue until someone on your team signs off." },
    { q: "Does it handle time zones?", a: "Scheduling always uses each location's local time zone, so a branch in another region publishes at its own peak hours." },
    { q: "How far ahead can I schedule?", a: "As far as you like — most teams plan a full month, and seasonal campaigns are often queued a quarter ahead." },
  ],
  ctaHeading: "Set your calendar once. Stay visible all year.",
  ctaText: "Book a free demo and we'll build your first 30-day posting schedule with you.",
};

export const reviewManagement: FeaturePageConfig = {
  slug: "/features/review-management",
  eyebrow: "Review Management",
  title: "Review Management",
  headline: "Reply to every review in seconds, not days.",
  subtitle:
    "Vizogen pulls every Google review into one inbox, detects sentiment and drafts a personalised reply you can send with one tap — so your rating, response rate and local ranking all keep climbing.",
  image: reviewsImg.url,
  imageAlt: "Vizogen Google Reviews dashboard with AI replies and sentiment analytics",
  heroBadge: { value: "100%", label: "reviews answered" },
  stats: [
    { value: "<2 min", label: "Average response time" },
    { value: "+0.6★", label: "Typical rating lift" },
    { value: "24/7", label: "New review monitoring" },
  ],
  how: [
    { n: "01", title: "Sync your reviews", desc: "All past and incoming Google reviews land in a single inbox across every location." },
    { n: "02", title: "Read the sentiment", desc: "Each review is tagged positive, neutral or negative and grouped by the topic customers mention." },
    { n: "03", title: "Generate a reply", desc: "AI writes a specific, human-sounding response that references what the customer actually said." },
    { n: "04", title: "Send and track", desc: "Publish the reply to Google, then watch response rate and rating trends in your dashboard." },
  ],
  capabilities: [
    { icon: MessageSquareHeart, title: "AI reply drafts", desc: "Context-aware replies in your tone, ready to edit — never a copy-paste template." },
    { icon: Star, title: "Rating dashboard", desc: "Track average rating, review volume and response rate over time per location." },
    { icon: Filter, title: "Smart filters", desc: "Sort by unanswered, low-star or keyword so urgent feedback never slips through." },
    { icon: BellRing, title: "Instant alerts", desc: "Get notified the moment a 1 or 2-star review arrives so you can recover the customer fast." },
    { icon: ShieldCheck, title: "Escalation notes", desc: "Add internal notes and assign follow-ups to staff without leaving the inbox." },
    { icon: BarChart3, title: "Theme insights", desc: "See recurring complaints and compliments to fix real operational issues." },
  ],
  without: [
    "Reviews sitting unanswered for weeks",
    "Same generic 'Thank you!' on every review",
    "Missing angry reviews until damage is done",
    "No visibility across multiple branches",
    "Rating slowly drifting downward",
    "Feedback themes never analysed",
  ],
  withVizogen: [
    "Every review answered within minutes",
    "Personalised, specific replies each time",
    "Instant alerts on negative feedback",
    "One inbox for all locations",
    "Rating and response rate trending up",
    "Clear insight into what customers repeat",
  ],
  faqs: [
    { q: "Can replies be sent automatically?", a: "You choose. Auto-send positive replies and keep negative ones in manual review, or approve everything yourself." },
    { q: "Does it work with old reviews too?", a: "Yes — Vizogen imports your review history so you can clear a backlog of unanswered feedback." },
    { q: "Can it remove bad reviews?", a: "No tool can delete genuine reviews. Vizogen helps you respond well, resolve issues and earn more positive reviews to lift your average." },
    { q: "Do replies sound robotic?", a: "Each draft references the reviewer's specific points and follows your chosen tone, so it reads like a real person from your team." },
  ],
  ctaHeading: "Turn reviews into your strongest sales channel.",
  ctaText: "See your own review inbox in a free demo — including AI replies drafted for real reviews on your profile.",
};

export const magicQr: FeaturePageConfig = {
  slug: "/features/magic-qr",
  eyebrow: "Magic QR",
  title: "Magic QR",
  headline: "Collect more 5-star reviews, catch problems privately.",
  subtitle:
    "Magic QR gives every customer one scan. Happy customers are routed straight to your Google review page; unhappy customers land on a private feedback form that reaches you instead of the public internet.",
  image: magicQrImg,
  imageAlt: "Branded Magic QR review stand next to a phone showing a star rating screen",
  heroBadge: { value: "5x", label: "more review requests" },
  stats: [
    { value: "1 scan", label: "From counter to review" },
    { value: "4-5★", label: "Routed to Google" },
    { value: "1-3★", label: "Routed to you privately" },
  ],
  how: [
    { n: "01", title: "Generate your QR", desc: "Create a branded QR code for each location or staff member in a couple of clicks." },
    { n: "02", title: "Put it in front of customers", desc: "Print table stands, bill stickers, packaging labels or share the link over WhatsApp." },
    { n: "03", title: "Customer rates you", desc: "A quick mobile screen asks for a star rating — no app, no login, no friction." },
    { n: "04", title: "Smart routing kicks in", desc: "High ratings go to Google. Low ratings open a private form so you can fix it first." },
  ],
  capabilities: [
    { icon: QrCode, title: "Branded QR designs", desc: "Add your logo and colours, then download print-ready files for stands and stickers." },
    { icon: Filter, title: "Sentiment routing", desc: "Positive experiences become public reviews; negative ones become private feedback." },
    { icon: Smartphone, title: "Zero-friction mobile flow", desc: "Loads instantly on any phone browser — no downloads or accounts required." },
    { icon: Palette, title: "Custom landing page", desc: "Your business name, logo and message on the rating screen build trust before the tap." },
    { icon: MapPin, title: "Per-location codes", desc: "Track which branch, counter or staff member drives the most reviews." },
    { icon: BarChart3, title: "Scan analytics", desc: "See scans, conversion to review and average rating over any date range." },
  ],
  without: [
    "Awkwardly asking customers for reviews",
    "Staff forgetting to request feedback",
    "Angry customers venting publicly first",
    "No idea which branch collects reviews",
    "Long links customers never open",
    "Review count stuck for months",
  ],
  withVizogen: [
    "One scan replaces the awkward ask",
    "Every visit is a review opportunity",
    "Complaints reach you privately first",
    "Per-location and per-staff tracking",
    "Instant mobile flow, no typing links",
    "Steady stream of new 5-star reviews",
  ],
  faqs: [
    { q: "Is review gating allowed by Google?", a: "Magic QR never blocks anyone from reviewing you — the Google option stays available. It simply offers a private feedback path first so you can resolve issues." },
    { q: "Do customers need an app?", a: "No. The QR opens a lightweight web page in their phone browser." },
    { q: "Can I print the QR myself?", a: "Yes — download high-resolution files for table tents, stickers, receipts or packaging." },
    { q: "Can each staff member have their own code?", a: "Yes, and you can compare performance to reward the people bringing in the most reviews." },
  ],
  ctaHeading: "Put a review engine on every counter.",
  ctaText: "Get your branded Magic QR in a free demo and start collecting reviews the same day.",
};
