/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BakeryMarketingSoftwareRouteImport } from './routes/bakery-marketing-software'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CarGarageMarketingSoftwareRouteImport } from './routes/car-garage-marketing-software'
import { Route as ClinicMarketingSoftwareRouteImport } from './routes/clinic-marketing-software'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EducationMarketingSoftwareRouteImport } from './routes/education-marketing-software'
import { Route as GymMarketingSoftwareRouteImport } from './routes/gym-marketing-software'
import { Route as HandymanMarketingSoftwareRouteImport } from './routes/handyman-marketing-software'
import { Route as HowToConnectGbpRouteImport } from './routes/how-to-connect-gbp'
import { Route as HowToCreatePostRouteImport } from './routes/how-to-create-post'
import { Route as HowToGenerateMagicQrRouteImport } from './routes/how-to-generate-magic-qr'
import { Route as HowToPostOnGbpRouteImport } from './routes/how-to-post-on-gbp'
import { Route as HowToReplyReviewRouteImport } from './routes/how-to-reply-review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficialPartnerRouteImport } from './routes/official-partner'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PestControlMarketingSoftwareRouteImport } from './routes/pest-control-marketing-software'
import { Route as PostManagementRouteImport } from './routes/post-management'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RealestateMarketingSoftwareRouteImport } from './routes/realestate-marketing-software'
import { Route as RestaurantMarketingSoftwareRouteImport } from './routes/restaurant-marketing-software'
import { Route as SalonMarketingSoftwareRouteImport } from './routes/salon-marketing-software'
import { Route as TourTravelMarketingSoftwareRouteImport } from './routes/tour-travel-marketing-software'
import { Route as YogaWellnessMarketingSoftwareRouteImport } from './routes/yoga-wellness-marketing-software'
import { Route as FeaturesAiPostGenerationRouteImport } from './routes/features.ai-post-generation'
import { Route as FeaturesMagicQrRouteImport } from './routes/features.magic-qr'
import { Route as FeaturesReviewManagementRouteImport } from './routes/features.review-management'
import { Route as FeaturesSmartSchedulingRouteImport } from './routes/features.smart-scheduling'
import { Route as ServicesLocalSeoRouteImport } from './routes/services.local-seo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryMarketingSoftwareRoute = BakeryMarketingSoftwareRouteImport.update({
  id: '/bakery-marketing-software',
  path: '/bakery-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarGarageMarketingSoftwareRoute =
  CarGarageMarketingSoftwareRouteImport.update({
    id: '/car-garage-marketing-software',
    path: '/car-garage-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClinicMarketingSoftwareRoute = ClinicMarketingSoftwareRouteImport.update({
  id: '/clinic-marketing-software',
  path: '/clinic-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationMarketingSoftwareRoute =
  EducationMarketingSoftwareRouteImport.update({
    id: '/education-marketing-software',
    path: '/education-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const GymMarketingSoftwareRoute = GymMarketingSoftwareRouteImport.update({
  id: '/gym-marketing-software',
  path: '/gym-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const HandymanMarketingSoftwareRoute =
  HandymanMarketingSoftwareRouteImport.update({
    id: '/handyman-marketing-software',
    path: '/handyman-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToConnectGbpRoute = HowToConnectGbpRouteImport.update({
  id: '/how-to-connect-gbp',
  path: '/how-to-connect-gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToCreatePostRoute = HowToCreatePostRouteImport.update({
  id: '/how-to-create-post',
  path: '/how-to-create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToGenerateMagicQrRoute = HowToGenerateMagicQrRouteImport.update({
  id: '/how-to-generate-magic-qr',
  path: '/how-to-generate-magic-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPostOnGbpRoute = HowToPostOnGbpRouteImport.update({
  id: '/how-to-post-on-gbp',
  path: '/how-to-post-on-gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToReplyReviewRoute = HowToReplyReviewRouteImport.update({
  id: '/how-to-reply-review',
  path: '/how-to-reply-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialPartnerRoute = OfficialPartnerRouteImport.update({
  id: '/official-partner',
  path: '/official-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PestControlMarketingSoftwareRoute =
  PestControlMarketingSoftwareRouteImport.update({
    id: '/pest-control-marketing-software',
    path: '/pest-control-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostManagementRoute = PostManagementRouteImport.update({
  id: '/post-management',
  path: '/post-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RealestateMarketingSoftwareRoute =
  RealestateMarketingSoftwareRouteImport.update({
    id: '/realestate-marketing-software',
    path: '/realestate-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantMarketingSoftwareRoute =
  RestaurantMarketingSoftwareRouteImport.update({
    id: '/restaurant-marketing-software',
    path: '/restaurant-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalonMarketingSoftwareRoute = SalonMarketingSoftwareRouteImport.update({
  id: '/salon-marketing-software',
  path: '/salon-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTravelMarketingSoftwareRoute =
  TourTravelMarketingSoftwareRouteImport.update({
    id: '/tour-travel-marketing-software',
    path: '/tour-travel-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const YogaWellnessMarketingSoftwareRoute =
  YogaWellnessMarketingSoftwareRouteImport.update({
    id: '/yoga-wellness-marketing-software',
    path: '/yoga-wellness-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesAiPostGenerationRoute =
  FeaturesAiPostGenerationRouteImport.update({
    id: '/features/ai-post-generation',
    path: '/features/ai-post-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesMagicQrRoute = FeaturesMagicQrRouteImport.update({
  id: '/features/magic-qr',
  path: '/features/magic-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesReviewManagementRoute =
  FeaturesReviewManagementRouteImport.update({
    id: '/features/review-management',
    path: '/features/review-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesSmartSchedulingRoute = FeaturesSmartSchedulingRouteImport.update({
  id: '/features/smart-scheduling',
  path: '/features/smart-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoRoute = ServicesLocalSeoRouteImport.update({
  id: '/services/local-seo',
  path: '/services/local-seo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bakery-marketing-software': typeof BakeryMarketingSoftwareRoute
  '/blog': typeof BlogRoute
  '/car-garage-marketing-software': typeof CarGarageMarketingSoftwareRoute
  '/clinic-marketing-software': typeof ClinicMarketingSoftwareRoute
  '/demo': typeof DemoRoute
  '/education-marketing-software': typeof EducationMarketingSoftwareRoute
  '/gym-marketing-software': typeof GymMarketingSoftwareRoute
  '/handyman-marketing-software': typeof HandymanMarketingSoftwareRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-generate-magic-qr': typeof HowToGenerateMagicQrRoute
  '/how-to-post-on-gbp': typeof HowToPostOnGbpRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
  '/official-partner': typeof OfficialPartnerRoute
  '/partner': typeof PartnerRoute
  '/pest-control-marketing-software': typeof PestControlMarketingSoftwareRoute
  '/post-management': typeof PostManagementRoute
  '/pricing': typeof PricingRoute
  '/realestate-marketing-software': typeof RealestateMarketingSoftwareRoute
  '/restaurant-marketing-software': typeof RestaurantMarketingSoftwareRoute
  '/salon-marketing-software': typeof SalonMarketingSoftwareRoute
  '/tour-travel-marketing-software': typeof TourTravelMarketingSoftwareRoute
  '/yoga-wellness-marketing-software': typeof YogaWellnessMarketingSoftwareRoute
  '/features/ai-post-generation': typeof FeaturesAiPostGenerationRoute
  '/features/magic-qr': typeof FeaturesMagicQrRoute
  '/features/review-management': typeof FeaturesReviewManagementRoute
  '/features/smart-scheduling': typeof FeaturesSmartSchedulingRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bakery-marketing-software': typeof BakeryMarketingSoftwareRoute
  '/blog': typeof BlogRoute
  '/car-garage-marketing-software': typeof CarGarageMarketingSoftwareRoute
  '/clinic-marketing-software': typeof ClinicMarketingSoftwareRoute
  '/demo': typeof DemoRoute
  '/education-marketing-software': typeof EducationMarketingSoftwareRoute
  '/gym-marketing-software': typeof GymMarketingSoftwareRoute
  '/handyman-marketing-software': typeof HandymanMarketingSoftwareRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-generate-magic-qr': typeof HowToGenerateMagicQrRoute
  '/how-to-post-on-gbp': typeof HowToPostOnGbpRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
  '/official-partner': typeof OfficialPartnerRoute
  '/partner': typeof PartnerRoute
  '/pest-control-marketing-software': typeof PestControlMarketingSoftwareRoute
  '/post-management': typeof PostManagementRoute
  '/pricing': typeof PricingRoute
  '/realestate-marketing-software': typeof RealestateMarketingSoftwareRoute
  '/restaurant-marketing-software': typeof RestaurantMarketingSoftwareRoute
  '/salon-marketing-software': typeof SalonMarketingSoftwareRoute
  '/tour-travel-marketing-software': typeof TourTravelMarketingSoftwareRoute
  '/yoga-wellness-marketing-software': typeof YogaWellnessMarketingSoftwareRoute
  '/features/ai-post-generation': typeof FeaturesAiPostGenerationRoute
  '/features/magic-qr': typeof FeaturesMagicQrRoute
  '/features/review-management': typeof FeaturesReviewManagementRoute
  '/features/smart-scheduling': typeof FeaturesSmartSchedulingRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bakery-marketing-software': typeof BakeryMarketingSoftwareRoute
  '/blog': typeof BlogRoute
  '/car-garage-marketing-software': typeof CarGarageMarketingSoftwareRoute
  '/clinic-marketing-software': typeof ClinicMarketingSoftwareRoute
  '/demo': typeof DemoRoute
  '/education-marketing-software': typeof EducationMarketingSoftwareRoute
  '/gym-marketing-software': typeof GymMarketingSoftwareRoute
  '/handyman-marketing-software': typeof HandymanMarketingSoftwareRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-generate-magic-qr': typeof HowToGenerateMagicQrRoute
  '/how-to-post-on-gbp': typeof HowToPostOnGbpRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
  '/official-partner': typeof OfficialPartnerRoute
  '/partner': typeof PartnerRoute
  '/pest-control-marketing-software': typeof PestControlMarketingSoftwareRoute
  '/post-management': typeof PostManagementRoute
  '/pricing': typeof PricingRoute
  '/realestate-marketing-software': typeof RealestateMarketingSoftwareRoute
  '/restaurant-marketing-software': typeof RestaurantMarketingSoftwareRoute
  '/salon-marketing-software': typeof SalonMarketingSoftwareRoute
  '/tour-travel-marketing-software': typeof TourTravelMarketingSoftwareRoute
  '/yoga-wellness-marketing-software': typeof YogaWellnessMarketingSoftwareRoute
  '/features/ai-post-generation': typeof FeaturesAiPostGenerationRoute
  '/features/magic-qr': typeof FeaturesMagicQrRoute
  '/features/review-management': typeof FeaturesReviewManagementRoute
  '/features/smart-scheduling': typeof FeaturesSmartSchedulingRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bakery-marketing-software'
    | '/blog'
    | '/car-garage-marketing-software'
    | '/clinic-marketing-software'
    | '/demo'
    | '/education-marketing-software'
    | '/gym-marketing-software'
    | '/handyman-marketing-software'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-generate-magic-qr'
    | '/how-to-post-on-gbp'
    | '/how-to-reply-review'
    | '/login'
    | '/official-partner'
    | '/partner'
    | '/pest-control-marketing-software'
    | '/post-management'
    | '/pricing'
    | '/realestate-marketing-software'
    | '/restaurant-marketing-software'
    | '/salon-marketing-software'
    | '/tour-travel-marketing-software'
    | '/yoga-wellness-marketing-software'
    | '/features/ai-post-generation'
    | '/features/magic-qr'
    | '/features/review-management'
    | '/features/smart-scheduling'
    | '/services/local-seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bakery-marketing-software'
    | '/blog'
    | '/car-garage-marketing-software'
    | '/clinic-marketing-software'
    | '/demo'
    | '/education-marketing-software'
    | '/gym-marketing-software'
    | '/handyman-marketing-software'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-generate-magic-qr'
    | '/how-to-post-on-gbp'
    | '/how-to-reply-review'
    | '/login'
    | '/official-partner'
    | '/partner'
    | '/pest-control-marketing-software'
    | '/post-management'
    | '/pricing'
    | '/realestate-marketing-software'
    | '/restaurant-marketing-software'
    | '/salon-marketing-software'
    | '/tour-travel-marketing-software'
    | '/yoga-wellness-marketing-software'
    | '/features/ai-post-generation'
    | '/features/magic-qr'
    | '/features/review-management'
    | '/features/smart-scheduling'
    | '/services/local-seo'
  id:
    | '__root__'
    | '/'
    | '/bakery-marketing-software'
    | '/blog'
    | '/car-garage-marketing-software'
    | '/clinic-marketing-software'
    | '/demo'
    | '/education-marketing-software'
    | '/gym-marketing-software'
    | '/handyman-marketing-software'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-generate-magic-qr'
    | '/how-to-post-on-gbp'
    | '/how-to-reply-review'
    | '/login'
    | '/official-partner'
    | '/partner'
    | '/pest-control-marketing-software'
    | '/post-management'
    | '/pricing'
    | '/realestate-marketing-software'
    | '/restaurant-marketing-software'
    | '/salon-marketing-software'
    | '/tour-travel-marketing-software'
    | '/yoga-wellness-marketing-software'
    | '/features/ai-post-generation'
    | '/features/magic-qr'
    | '/features/review-management'
    | '/features/smart-scheduling'
    | '/services/local-seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakeryMarketingSoftwareRoute: typeof BakeryMarketingSoftwareRoute
  BlogRoute: typeof BlogRoute
  CarGarageMarketingSoftwareRoute: typeof CarGarageMarketingSoftwareRoute
  ClinicMarketingSoftwareRoute: typeof ClinicMarketingSoftwareRoute
  DemoRoute: typeof DemoRoute
  EducationMarketingSoftwareRoute: typeof EducationMarketingSoftwareRoute
  GymMarketingSoftwareRoute: typeof GymMarketingSoftwareRoute
  HandymanMarketingSoftwareRoute: typeof HandymanMarketingSoftwareRoute
  HowToConnectGbpRoute: typeof HowToConnectGbpRoute
  HowToCreatePostRoute: typeof HowToCreatePostRoute
  HowToGenerateMagicQrRoute: typeof HowToGenerateMagicQrRoute
  HowToPostOnGbpRoute: typeof HowToPostOnGbpRoute
  HowToReplyReviewRoute: typeof HowToReplyReviewRoute
  LoginRoute: typeof LoginRoute
  OfficialPartnerRoute: typeof OfficialPartnerRoute
  PartnerRoute: typeof PartnerRoute
  PestControlMarketingSoftwareRoute: typeof PestControlMarketingSoftwareRoute
  PostManagementRoute: typeof PostManagementRoute
  PricingRoute: typeof PricingRoute
  RealestateMarketingSoftwareRoute: typeof RealestateMarketingSoftwareRoute
  RestaurantMarketingSoftwareRoute: typeof RestaurantMarketingSoftwareRoute
  SalonMarketingSoftwareRoute: typeof SalonMarketingSoftwareRoute
  TourTravelMarketingSoftwareRoute: typeof TourTravelMarketingSoftwareRoute
  YogaWellnessMarketingSoftwareRoute: typeof YogaWellnessMarketingSoftwareRoute
  FeaturesAiPostGenerationRoute: typeof FeaturesAiPostGenerationRoute
  FeaturesMagicQrRoute: typeof FeaturesMagicQrRoute
  FeaturesReviewManagementRoute: typeof FeaturesReviewManagementRoute
  FeaturesSmartSchedulingRoute: typeof FeaturesSmartSchedulingRoute
  ServicesLocalSeoRoute: typeof ServicesLocalSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery-marketing-software': {
      id: '/bakery-marketing-software'
      path: '/bakery-marketing-software'
      fullPath: '/bakery-marketing-software'
      preLoaderRoute: typeof BakeryMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-garage-marketing-software': {
      id: '/car-garage-marketing-software'
      path: '/car-garage-marketing-software'
      fullPath: '/car-garage-marketing-software'
      preLoaderRoute: typeof CarGarageMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-marketing-software': {
      id: '/clinic-marketing-software'
      path: '/clinic-marketing-software'
      fullPath: '/clinic-marketing-software'
      preLoaderRoute: typeof ClinicMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-marketing-software': {
      id: '/education-marketing-software'
      path: '/education-marketing-software'
      fullPath: '/education-marketing-software'
      preLoaderRoute: typeof EducationMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-marketing-software': {
      id: '/gym-marketing-software'
      path: '/gym-marketing-software'
      fullPath: '/gym-marketing-software'
      preLoaderRoute: typeof GymMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handyman-marketing-software': {
      id: '/handyman-marketing-software'
      path: '/handyman-marketing-software'
      fullPath: '/handyman-marketing-software'
      preLoaderRoute: typeof HandymanMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-connect-gbp': {
      id: '/how-to-connect-gbp'
      path: '/how-to-connect-gbp'
      fullPath: '/how-to-connect-gbp'
      preLoaderRoute: typeof HowToConnectGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-create-post': {
      id: '/how-to-create-post'
      path: '/how-to-create-post'
      fullPath: '/how-to-create-post'
      preLoaderRoute: typeof HowToCreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-generate-magic-qr': {
      id: '/how-to-generate-magic-qr'
      path: '/how-to-generate-magic-qr'
      fullPath: '/how-to-generate-magic-qr'
      preLoaderRoute: typeof HowToGenerateMagicQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-post-on-gbp': {
      id: '/how-to-post-on-gbp'
      path: '/how-to-post-on-gbp'
      fullPath: '/how-to-post-on-gbp'
      preLoaderRoute: typeof HowToPostOnGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-reply-review': {
      id: '/how-to-reply-review'
      path: '/how-to-reply-review'
      fullPath: '/how-to-reply-review'
      preLoaderRoute: typeof HowToReplyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official-partner': {
      id: '/official-partner'
      path: '/official-partner'
      fullPath: '/official-partner'
      preLoaderRoute: typeof OfficialPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-control-marketing-software': {
      id: '/pest-control-marketing-software'
      path: '/pest-control-marketing-software'
      fullPath: '/pest-control-marketing-software'
      preLoaderRoute: typeof PestControlMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-management': {
      id: '/post-management'
      path: '/post-management'
      fullPath: '/post-management'
      preLoaderRoute: typeof PostManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realestate-marketing-software': {
      id: '/realestate-marketing-software'
      path: '/realestate-marketing-software'
      fullPath: '/realestate-marketing-software'
      preLoaderRoute: typeof RealestateMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-marketing-software': {
      id: '/restaurant-marketing-software'
      path: '/restaurant-marketing-software'
      fullPath: '/restaurant-marketing-software'
      preLoaderRoute: typeof RestaurantMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-marketing-software': {
      id: '/salon-marketing-software'
      path: '/salon-marketing-software'
      fullPath: '/salon-marketing-software'
      preLoaderRoute: typeof SalonMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-travel-marketing-software': {
      id: '/tour-travel-marketing-software'
      path: '/tour-travel-marketing-software'
      fullPath: '/tour-travel-marketing-software'
      preLoaderRoute: typeof TourTravelMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-wellness-marketing-software': {
      id: '/yoga-wellness-marketing-software'
      path: '/yoga-wellness-marketing-software'
      fullPath: '/yoga-wellness-marketing-software'
      preLoaderRoute: typeof YogaWellnessMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/ai-post-generation': {
      id: '/features/ai-post-generation'
      path: '/features/ai-post-generation'
      fullPath: '/features/ai-post-generation'
      preLoaderRoute: typeof FeaturesAiPostGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/magic-qr': {
      id: '/features/magic-qr'
      path: '/features/magic-qr'
      fullPath: '/features/magic-qr'
      preLoaderRoute: typeof FeaturesMagicQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/review-management': {
      id: '/features/review-management'
      path: '/features/review-management'
      fullPath: '/features/review-management'
      preLoaderRoute: typeof FeaturesReviewManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/smart-scheduling': {
      id: '/features/smart-scheduling'
      path: '/features/smart-scheduling'
      fullPath: '/features/smart-scheduling'
      preLoaderRoute: typeof FeaturesSmartSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo': {
      id: '/services/local-seo'
      path: '/services/local-seo'
      fullPath: '/services/local-seo'
      preLoaderRoute: typeof ServicesLocalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakeryMarketingSoftwareRoute: BakeryMarketingSoftwareRoute,
  BlogRoute: BlogRoute,
  CarGarageMarketingSoftwareRoute: CarGarageMarketingSoftwareRoute,
  ClinicMarketingSoftwareRoute: ClinicMarketingSoftwareRoute,
  DemoRoute: DemoRoute,
  EducationMarketingSoftwareRoute: EducationMarketingSoftwareRoute,
  GymMarketingSoftwareRoute: GymMarketingSoftwareRoute,
  HandymanMarketingSoftwareRoute: HandymanMarketingSoftwareRoute,
  HowToConnectGbpRoute: HowToConnectGbpRoute,
  HowToCreatePostRoute: HowToCreatePostRoute,
  HowToGenerateMagicQrRoute: HowToGenerateMagicQrRoute,
  HowToPostOnGbpRoute: HowToPostOnGbpRoute,
  HowToReplyReviewRoute: HowToReplyReviewRoute,
  LoginRoute: LoginRoute,
  OfficialPartnerRoute: OfficialPartnerRoute,
  PartnerRoute: PartnerRoute,
  PestControlMarketingSoftwareRoute: PestControlMarketingSoftwareRoute,
  PostManagementRoute: PostManagementRoute,
  PricingRoute: PricingRoute,
  RealestateMarketingSoftwareRoute: RealestateMarketingSoftwareRoute,
  RestaurantMarketingSoftwareRoute: RestaurantMarketingSoftwareRoute,
  SalonMarketingSoftwareRoute: SalonMarketingSoftwareRoute,
  TourTravelMarketingSoftwareRoute: TourTravelMarketingSoftwareRoute,
  YogaWellnessMarketingSoftwareRoute: YogaWellnessMarketingSoftwareRoute,
  FeaturesAiPostGenerationRoute: FeaturesAiPostGenerationRoute,
  FeaturesMagicQrRoute: FeaturesMagicQrRoute,
  FeaturesReviewManagementRoute: FeaturesReviewManagementRoute,
  FeaturesSmartSchedulingRoute: FeaturesSmartSchedulingRoute,
  ServicesLocalSeoRoute: ServicesLocalSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
