/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CrmRouteImport } from './routes/_crm'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BakeryMarketingSoftwareRouteImport } from './routes/bakery-marketing-software'
import { Route as CarGarageMarketingSoftwareRouteImport } from './routes/car-garage-marketing-software'
import { Route as ClinicMarketingSoftwareRouteImport } from './routes/clinic-marketing-software'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EducationMarketingSoftwareRouteImport } from './routes/education-marketing-software'
import { Route as GymMarketingSoftwareRouteImport } from './routes/gym-marketing-software'
import { Route as HandymanMarketingSoftwareRouteImport } from './routes/handyman-marketing-software'
import { Route as HowToConnectGbpRouteImport } from './routes/how-to-connect-gbp'
import { Route as HowToCreatePostRouteImport } from './routes/how-to-create-post'
import { Route as HowToGenerateMagicQrRouteImport } from './routes/how-to-generate-magic-qr'
import { Route as HowToPostOnGbpRouteImport } from './routes/how-to-post-on-gbp'
import { Route as HowToReplyReviewRouteImport } from './routes/how-to-reply-review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficialPartnerRouteImport } from './routes/official-partner'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PestControlMarketingSoftwareRouteImport } from './routes/pest-control-marketing-software'
import { Route as PostManagementRouteImport } from './routes/post-management'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RealestateMarketingSoftwareRouteImport } from './routes/realestate-marketing-software'
import { Route as RestaurantMarketingSoftwareRouteImport } from './routes/restaurant-marketing-software'
import { Route as SalonMarketingSoftwareRouteImport } from './routes/salon-marketing-software'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TourTravelMarketingSoftwareRouteImport } from './routes/tour-travel-marketing-software'
import { Route as YogaWellnessMarketingSoftwareRouteImport } from './routes/yoga-wellness-marketing-software'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CrmCrmRouteImport } from './routes/_crm/crm'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CrmLoginRouteImport } from './routes/crm.login'
import { Route as FeaturesAiPostGenerationRouteImport } from './routes/features.ai-post-generation'
import { Route as FeaturesMagicQrRouteImport } from './routes/features.magic-qr'
import { Route as FeaturesReviewManagementRouteImport } from './routes/features.review-management'
import { Route as FeaturesSmartSchedulingRouteImport } from './routes/features.smart-scheduling'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ServicesLocalSeoRouteImport } from './routes/services.local-seo'
import { Route as ServicesLocalSeoAhmedabadRouteImport } from './routes/services.local-seo-ahmedabad'
import { Route as ServicesLocalSeoBangaloreRouteImport } from './routes/services.local-seo-bangalore'
import { Route as ServicesLocalSeoChennaiRouteImport } from './routes/services.local-seo-chennai'
import { Route as ServicesLocalSeoDelhiRouteImport } from './routes/services.local-seo-delhi'
import { Route as ServicesLocalSeoGujaratRouteImport } from './routes/services.local-seo-gujarat'
import { Route as ServicesLocalSeoHyderabadRouteImport } from './routes/services.local-seo-hyderabad'
import { Route as ServicesLocalSeoJaipurRouteImport } from './routes/services.local-seo-jaipur'
import { Route as ServicesLocalSeoKolkataRouteImport } from './routes/services.local-seo-kolkata'
import { Route as ServicesLocalSeoLucknowRouteImport } from './routes/services.local-seo-lucknow'
import { Route as ServicesLocalSeoMumbaiRouteImport } from './routes/services.local-seo-mumbai'
import { Route as ServicesLocalSeoPuneRouteImport } from './routes/services.local-seo-pune'
import { Route as ServicesLocalSeoRajkotRouteImport } from './routes/services.local-seo-rajkot'
import { Route as ServicesLocalSeoSuratRouteImport } from './routes/services.local-seo-surat'
import { Route as ServicesLocalSeoVadodaraRouteImport } from './routes/services.local-seo-vadodara'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardMagicQrRouteImport } from './routes/_authenticated/dashboard.magic-qr'
import { Route as AuthenticatedDashboardPostsRouteImport } from './routes/_authenticated/dashboard.posts'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard.reviews'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as CrmCrmIndexRouteImport } from './routes/_crm/crm.index'
import { Route as CrmCrmLeadsRouteImport } from './routes/_crm/crm.leads'
import { Route as CrmCrmProposalsRouteImport } from './routes/_crm/crm.proposals'
import { Route as CrmCrmReportsRouteImport } from './routes/_crm/crm.reports'
import { Route as CrmCrmSettingsRouteImport } from './routes/_crm/crm.settings'
import { Route as CrmCrmTeamRouteImport } from './routes/_crm/crm.team'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as CrmCrmLeadIdRouteImport } from './routes/_crm/crm.lead.$id'
import { Route as ApiPublicCronPublishDueRouteImport } from './routes/api/public/cron/publish-due'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/_crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryMarketingSoftwareRoute = BakeryMarketingSoftwareRouteImport.update({
  id: '/bakery-marketing-software',
  path: '/bakery-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const CarGarageMarketingSoftwareRoute =
  CarGarageMarketingSoftwareRouteImport.update({
    id: '/car-garage-marketing-software',
    path: '/car-garage-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClinicMarketingSoftwareRoute = ClinicMarketingSoftwareRouteImport.update({
  id: '/clinic-marketing-software',
  path: '/clinic-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationMarketingSoftwareRoute =
  EducationMarketingSoftwareRouteImport.update({
    id: '/education-marketing-software',
    path: '/education-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const GymMarketingSoftwareRoute = GymMarketingSoftwareRouteImport.update({
  id: '/gym-marketing-software',
  path: '/gym-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const HandymanMarketingSoftwareRoute =
  HandymanMarketingSoftwareRouteImport.update({
    id: '/handyman-marketing-software',
    path: '/handyman-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToConnectGbpRoute = HowToConnectGbpRouteImport.update({
  id: '/how-to-connect-gbp',
  path: '/how-to-connect-gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToCreatePostRoute = HowToCreatePostRouteImport.update({
  id: '/how-to-create-post',
  path: '/how-to-create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToGenerateMagicQrRoute = HowToGenerateMagicQrRouteImport.update({
  id: '/how-to-generate-magic-qr',
  path: '/how-to-generate-magic-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPostOnGbpRoute = HowToPostOnGbpRouteImport.update({
  id: '/how-to-post-on-gbp',
  path: '/how-to-post-on-gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToReplyReviewRoute = HowToReplyReviewRouteImport.update({
  id: '/how-to-reply-review',
  path: '/how-to-reply-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialPartnerRoute = OfficialPartnerRouteImport.update({
  id: '/official-partner',
  path: '/official-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PestControlMarketingSoftwareRoute =
  PestControlMarketingSoftwareRouteImport.update({
    id: '/pest-control-marketing-software',
    path: '/pest-control-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostManagementRoute = PostManagementRouteImport.update({
  id: '/post-management',
  path: '/post-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RealestateMarketingSoftwareRoute =
  RealestateMarketingSoftwareRouteImport.update({
    id: '/realestate-marketing-software',
    path: '/realestate-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantMarketingSoftwareRoute =
  RestaurantMarketingSoftwareRouteImport.update({
    id: '/restaurant-marketing-software',
    path: '/restaurant-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalonMarketingSoftwareRoute = SalonMarketingSoftwareRouteImport.update({
  id: '/salon-marketing-software',
  path: '/salon-marketing-software',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TourTravelMarketingSoftwareRoute =
  TourTravelMarketingSoftwareRouteImport.update({
    id: '/tour-travel-marketing-software',
    path: '/tour-travel-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const YogaWellnessMarketingSoftwareRoute =
  YogaWellnessMarketingSoftwareRouteImport.update({
    id: '/yoga-wellness-marketing-software',
    path: '/yoga-wellness-marketing-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CrmCrmRoute = CrmCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CrmRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLoginRoute = CrmLoginRouteImport.update({
  id: '/crm/login',
  path: '/crm/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesAiPostGenerationRoute =
  FeaturesAiPostGenerationRouteImport.update({
    id: '/features/ai-post-generation',
    path: '/features/ai-post-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesMagicQrRoute = FeaturesMagicQrRouteImport.update({
  id: '/features/magic-qr',
  path: '/features/magic-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesReviewManagementRoute =
  FeaturesReviewManagementRouteImport.update({
    id: '/features/review-management',
    path: '/features/review-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const FeaturesSmartSchedulingRoute = FeaturesSmartSchedulingRouteImport.update({
  id: '/features/smart-scheduling',
  path: '/features/smart-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoRoute = ServicesLocalSeoRouteImport.update({
  id: '/services/local-seo',
  path: '/services/local-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoAhmedabadRoute =
  ServicesLocalSeoAhmedabadRouteImport.update({
    id: '/services/local-seo-ahmedabad',
    path: '/services/local-seo-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLocalSeoBangaloreRoute =
  ServicesLocalSeoBangaloreRouteImport.update({
    id: '/services/local-seo-bangalore',
    path: '/services/local-seo-bangalore',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLocalSeoChennaiRoute = ServicesLocalSeoChennaiRouteImport.update({
  id: '/services/local-seo-chennai',
  path: '/services/local-seo-chennai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoDelhiRoute = ServicesLocalSeoDelhiRouteImport.update({
  id: '/services/local-seo-delhi',
  path: '/services/local-seo-delhi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoGujaratRoute = ServicesLocalSeoGujaratRouteImport.update({
  id: '/services/local-seo-gujarat',
  path: '/services/local-seo-gujarat',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoHyderabadRoute =
  ServicesLocalSeoHyderabadRouteImport.update({
    id: '/services/local-seo-hyderabad',
    path: '/services/local-seo-hyderabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLocalSeoJaipurRoute = ServicesLocalSeoJaipurRouteImport.update({
  id: '/services/local-seo-jaipur',
  path: '/services/local-seo-jaipur',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoKolkataRoute = ServicesLocalSeoKolkataRouteImport.update({
  id: '/services/local-seo-kolkata',
  path: '/services/local-seo-kolkata',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoLucknowRoute = ServicesLocalSeoLucknowRouteImport.update({
  id: '/services/local-seo-lucknow',
  path: '/services/local-seo-lucknow',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoMumbaiRoute = ServicesLocalSeoMumbaiRouteImport.update({
  id: '/services/local-seo-mumbai',
  path: '/services/local-seo-mumbai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoPuneRoute = ServicesLocalSeoPuneRouteImport.update({
  id: '/services/local-seo-pune',
  path: '/services/local-seo-pune',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoRajkotRoute = ServicesLocalSeoRajkotRouteImport.update({
  id: '/services/local-seo-rajkot',
  path: '/services/local-seo-rajkot',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoSuratRoute = ServicesLocalSeoSuratRouteImport.update({
  id: '/services/local-seo-surat',
  path: '/services/local-seo-surat',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLocalSeoVadodaraRoute =
  ServicesLocalSeoVadodaraRouteImport.update({
    id: '/services/local-seo-vadodara',
    path: '/services/local-seo-vadodara',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMagicQrRoute =
  AuthenticatedDashboardMagicQrRouteImport.update({
    id: '/magic-qr',
    path: '/magic-qr',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPostsRoute =
  AuthenticatedDashboardPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const CrmCrmIndexRoute = CrmCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmCrmRoute,
} as any)
const CrmCrmLeadsRoute = CrmCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmCrmRoute,
} as any)
const CrmCrmProposalsRoute = CrmCrmProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => CrmCrmRoute,
} as any)
const CrmCrmReportsRoute = CrmCrmReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CrmCrmRoute,
} as any)
const CrmCrmSettingsRoute = CrmCrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CrmCrmRoute,
} as any)
const CrmCrmTeamRoute = CrmCrmTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CrmCrmRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCrmLeadIdRoute = CrmCrmLeadIdRouteImport.update({
  id: '/lead/$id',
  path: '/lead/$id',
  getParentRoute: () => CrmCrmRoute,
} as any)
const ApiPublicCronPublishDueRoute = ApiPublicCronPublishDueRouteImport.update({
  id: '/api/public/cron/publish-due',
  path: '/api/public/cron/publish-due',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bakery-marketing-software': typeof BakeryMarketingSoftwareRoute
  '/car-garage-marketing-software': typeof CarGarageMarketingSoftwareRoute
  '/clinic-marketing-software': typeof ClinicMarketingSoftwareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/education-marketing-software': typeof EducationMarketingSoftwareRoute
  '/gym-marketing-software': typeof GymMarketingSoftwareRoute
  '/handyman-marketing-software': typeof HandymanMarketingSoftwareRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-generate-magic-qr': typeof HowToGenerateMagicQrRoute
  '/how-to-post-on-gbp': typeof HowToPostOnGbpRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
  '/official-partner': typeof OfficialPartnerRoute
  '/partner': typeof PartnerRoute
  '/pest-control-marketing-software': typeof PestControlMarketingSoftwareRoute
  '/post-management': typeof PostManagementRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/realestate-marketing-software': typeof RealestateMarketingSoftwareRoute
  '/restaurant-marketing-software': typeof RestaurantMarketingSoftwareRoute
  '/salon-marketing-software': typeof SalonMarketingSoftwareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tour-travel-marketing-software': typeof TourTravelMarketingSoftwareRoute
  '/yoga-wellness-marketing-software': typeof YogaWellnessMarketingSoftwareRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/crm': typeof CrmCrmRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/crm/login': typeof CrmLoginRoute
  '/features/ai-post-generation': typeof FeaturesAiPostGenerationRoute
  '/features/magic-qr': typeof FeaturesMagicQrRoute
  '/features/review-management': typeof FeaturesReviewManagementRoute
  '/features/smart-scheduling': typeof FeaturesSmartSchedulingRoute
  '/r/$slug': typeof RSlugRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
  '/services/local-seo-ahmedabad': typeof ServicesLocalSeoAhmedabadRoute
  '/services/local-seo-bangalore': typeof ServicesLocalSeoBangaloreRoute
  '/services/local-seo-chennai': typeof ServicesLocalSeoChennaiRoute
  '/services/local-seo-delhi': typeof ServicesLocalSeoDelhiRoute
  '/services/local-seo-gujarat': typeof ServicesLocalSeoGujaratRoute
  '/services/local-seo-hyderabad': typeof ServicesLocalSeoHyderabadRoute
  '/services/local-seo-jaipur': typeof ServicesLocalSeoJaipurRoute
  '/services/local-seo-kolkata': typeof ServicesLocalSeoKolkataRoute
  '/services/local-seo-lucknow': typeof ServicesLocalSeoLucknowRoute
  '/services/local-seo-mumbai': typeof ServicesLocalSeoMumbaiRoute
  '/services/local-seo-pune': typeof ServicesLocalSeoPuneRoute
  '/services/local-seo-rajkot': typeof ServicesLocalSeoRajkotRoute
  '/services/local-seo-surat': typeof ServicesLocalSeoSuratRoute
  '/services/local-seo-vadodara': typeof ServicesLocalSeoVadodaraRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/magic-qr': typeof AuthenticatedDashboardMagicQrRoute
  '/dashboard/posts': typeof AuthenticatedDashboardPostsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/crm/leads': typeof CrmCrmLeadsRoute
  '/crm/proposals': typeof CrmCrmProposalsRoute
  '/crm/reports': typeof CrmCrmReportsRoute
  '/crm/settings': typeof CrmCrmSettingsRoute
  '/crm/team': typeof CrmCrmTeamRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/crm/': typeof CrmCrmIndexRoute
  '/crm/lead/$id': typeof CrmCrmLeadIdRoute
  '/api/public/cron/publish-due': typeof ApiPublicCronPublishDueRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bakery-marketing-software': typeof BakeryMarketingSoftwareRoute
  '/car-garage-marketing-software': typeof CarGarageMarketingSoftwareRoute
  '/clinic-marketing-software': typeof ClinicMarketingSoftwareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/education-marketing-software': typeof EducationMarketingSoftwareRoute
  '/gym-marketing-software': typeof GymMarketingSoftwareRoute
  '/handyman-marketing-software': typeof HandymanMarketingSoftwareRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-generate-magic-qr': typeof HowToGenerateMagicQrRoute
  '/how-to-post-on-gbp': typeof HowToPostOnGbpRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
  '/official-partner': typeof OfficialPartnerRoute
  '/partner': typeof PartnerRoute
  '/pest-control-marketing-software': typeof PestControlMarketingSoftwareRoute
  '/post-management': typeof PostManagementRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/realestate-marketing-software': typeof RealestateMarketingSoftwareRoute
  '/restaurant-marketing-software': typeof RestaurantMarketingSoftwareRoute
  '/salon-marketing-software': typeof SalonMarketingSoftwareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tour-travel-marketing-software': typeof TourTravelMarketingSoftwareRoute
  '/yoga-wellness-marketing-software': typeof YogaWellnessMarketingSoftwareRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/crm/login': typeof CrmLoginRoute
  '/features/ai-post-generation': typeof FeaturesAiPostGenerationRoute
  '/features/magic-qr': typeof FeaturesMagicQrRoute
  '/features/review-management': typeof FeaturesReviewManagementRoute
  '/features/smart-scheduling': typeof FeaturesSmartSchedulingRoute
  '/r/$slug': typeof RSlugRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
  '/services/local-seo-ahmedabad': typeof ServicesLocalSeoAhmedabadRoute
  '/services/local-seo-bangalore': typeof ServicesLocalSeoBangaloreRoute
  '/services/local-seo-chennai': typeof ServicesLocalSeoChennaiRoute
  '/services/local-seo-delhi': typeof ServicesLocalSeoDelhiRoute
  '/services/local-seo-gujarat': typeof ServicesLocalSeoGujaratRoute
  '/services/local-seo-hyderabad': typeof ServicesLocalSeoHyderabadRoute
  '/services/local-seo-jaipur': typeof ServicesLocalSeoJaipurRoute
  '/services/local-seo-kolkata': typeof ServicesLocalSeoKolkataRoute
  '/services/local-seo-lucknow': typeof ServicesLocalSeoLucknowRoute
  '/services/local-seo-mumbai': typeof ServicesLocalSeoMumbaiRoute
  '/services/local-seo-pune': typeof ServicesLocalSeoPuneRoute
  '/services/local-seo-rajkot': typeof ServicesLocalSeoRajkotRoute
  '/services/local-seo-surat': typeof ServicesLocalSeoSuratRoute
  '/services/local-seo-vadodara': typeof ServicesLocalSeoVadodaraRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard/magic-qr': typeof AuthenticatedDashboardMagicQrRoute
  '/dashboard/posts': typeof AuthenticatedDashboardPostsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/crm/leads': typeof CrmCrmLeadsRoute
  '/crm/proposals': typeof CrmCrmProposalsRoute
  '/crm/reports': typeof CrmCrmReportsRoute
  '/crm/settings': typeof CrmCrmSettingsRoute
  '/crm/team': typeof CrmCrmTeamRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/crm': typeof CrmCrmIndexRoute
  '/crm/lead/$id': typeof CrmCrmLeadIdRoute
  '/api/public/cron/publish-due': typeof ApiPublicCronPublishDueRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_crm': typeof CrmRouteWithChildren
  '/auth': typeof AuthRoute
  '/bakery-marketing-software': typeof BakeryMarketingSoftwareRoute
  '/car-garage-marketing-software': typeof CarGarageMarketingSoftwareRoute
  '/clinic-marketing-software': typeof ClinicMarketingSoftwareRoute
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/education-marketing-software': typeof EducationMarketingSoftwareRoute
  '/gym-marketing-software': typeof GymMarketingSoftwareRoute
  '/handyman-marketing-software': typeof HandymanMarketingSoftwareRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-generate-magic-qr': typeof HowToGenerateMagicQrRoute
  '/how-to-post-on-gbp': typeof HowToPostOnGbpRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
  '/official-partner': typeof OfficialPartnerRoute
  '/partner': typeof PartnerRoute
  '/pest-control-marketing-software': typeof PestControlMarketingSoftwareRoute
  '/post-management': typeof PostManagementRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/realestate-marketing-software': typeof RealestateMarketingSoftwareRoute
  '/restaurant-marketing-software': typeof RestaurantMarketingSoftwareRoute
  '/salon-marketing-software': typeof SalonMarketingSoftwareRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tour-travel-marketing-software': typeof TourTravelMarketingSoftwareRoute
  '/yoga-wellness-marketing-software': typeof YogaWellnessMarketingSoftwareRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_crm/crm': typeof CrmCrmRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/crm/login': typeof CrmLoginRoute
  '/features/ai-post-generation': typeof FeaturesAiPostGenerationRoute
  '/features/magic-qr': typeof FeaturesMagicQrRoute
  '/features/review-management': typeof FeaturesReviewManagementRoute
  '/features/smart-scheduling': typeof FeaturesSmartSchedulingRoute
  '/r/$slug': typeof RSlugRoute
  '/services/local-seo': typeof ServicesLocalSeoRoute
  '/services/local-seo-ahmedabad': typeof ServicesLocalSeoAhmedabadRoute
  '/services/local-seo-bangalore': typeof ServicesLocalSeoBangaloreRoute
  '/services/local-seo-chennai': typeof ServicesLocalSeoChennaiRoute
  '/services/local-seo-delhi': typeof ServicesLocalSeoDelhiRoute
  '/services/local-seo-gujarat': typeof ServicesLocalSeoGujaratRoute
  '/services/local-seo-hyderabad': typeof ServicesLocalSeoHyderabadRoute
  '/services/local-seo-jaipur': typeof ServicesLocalSeoJaipurRoute
  '/services/local-seo-kolkata': typeof ServicesLocalSeoKolkataRoute
  '/services/local-seo-lucknow': typeof ServicesLocalSeoLucknowRoute
  '/services/local-seo-mumbai': typeof ServicesLocalSeoMumbaiRoute
  '/services/local-seo-pune': typeof ServicesLocalSeoPuneRoute
  '/services/local-seo-rajkot': typeof ServicesLocalSeoRajkotRoute
  '/services/local-seo-surat': typeof ServicesLocalSeoSuratRoute
  '/services/local-seo-vadodara': typeof ServicesLocalSeoVadodaraRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/dashboard/magic-qr': typeof AuthenticatedDashboardMagicQrRoute
  '/_authenticated/dashboard/posts': typeof AuthenticatedDashboardPostsRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_crm/crm/leads': typeof CrmCrmLeadsRoute
  '/_crm/crm/proposals': typeof CrmCrmProposalsRoute
  '/_crm/crm/reports': typeof CrmCrmReportsRoute
  '/_crm/crm/settings': typeof CrmCrmSettingsRoute
  '/_crm/crm/team': typeof CrmCrmTeamRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_crm/crm/': typeof CrmCrmIndexRoute
  '/_crm/crm/lead/$id': typeof CrmCrmLeadIdRoute
  '/api/public/cron/publish-due': typeof ApiPublicCronPublishDueRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bakery-marketing-software'
    | '/car-garage-marketing-software'
    | '/clinic-marketing-software'
    | '/contact'
    | '/demo'
    | '/education-marketing-software'
    | '/gym-marketing-software'
    | '/handyman-marketing-software'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-generate-magic-qr'
    | '/how-to-post-on-gbp'
    | '/how-to-reply-review'
    | '/login'
    | '/official-partner'
    | '/partner'
    | '/pest-control-marketing-software'
    | '/post-management'
    | '/pricing'
    | '/privacy-policy'
    | '/realestate-marketing-software'
    | '/restaurant-marketing-software'
    | '/salon-marketing-software'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/tour-travel-marketing-software'
    | '/yoga-wellness-marketing-software'
    | '/dashboard'
    | '/crm'
    | '/blog/$slug'
    | '/crm/login'
    | '/features/ai-post-generation'
    | '/features/magic-qr'
    | '/features/review-management'
    | '/features/smart-scheduling'
    | '/r/$slug'
    | '/services/local-seo'
    | '/services/local-seo-ahmedabad'
    | '/services/local-seo-bangalore'
    | '/services/local-seo-chennai'
    | '/services/local-seo-delhi'
    | '/services/local-seo-gujarat'
    | '/services/local-seo-hyderabad'
    | '/services/local-seo-jaipur'
    | '/services/local-seo-kolkata'
    | '/services/local-seo-lucknow'
    | '/services/local-seo-mumbai'
    | '/services/local-seo-pune'
    | '/services/local-seo-rajkot'
    | '/services/local-seo-surat'
    | '/services/local-seo-vadodara'
    | '/blog/'
    | '/dashboard/magic-qr'
    | '/dashboard/posts'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/crm/leads'
    | '/crm/proposals'
    | '/crm/reports'
    | '/crm/settings'
    | '/crm/team'
    | '/api/public/leads'
    | '/dashboard/'
    | '/crm/'
    | '/crm/lead/$id'
    | '/api/public/cron/publish-due'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bakery-marketing-software'
    | '/car-garage-marketing-software'
    | '/clinic-marketing-software'
    | '/contact'
    | '/demo'
    | '/education-marketing-software'
    | '/gym-marketing-software'
    | '/handyman-marketing-software'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-generate-magic-qr'
    | '/how-to-post-on-gbp'
    | '/how-to-reply-review'
    | '/login'
    | '/official-partner'
    | '/partner'
    | '/pest-control-marketing-software'
    | '/post-management'
    | '/pricing'
    | '/privacy-policy'
    | '/realestate-marketing-software'
    | '/restaurant-marketing-software'
    | '/salon-marketing-software'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/tour-travel-marketing-software'
    | '/yoga-wellness-marketing-software'
    | '/blog/$slug'
    | '/crm/login'
    | '/features/ai-post-generation'
    | '/features/magic-qr'
    | '/features/review-management'
    | '/features/smart-scheduling'
    | '/r/$slug'
    | '/services/local-seo'
    | '/services/local-seo-ahmedabad'
    | '/services/local-seo-bangalore'
    | '/services/local-seo-chennai'
    | '/services/local-seo-delhi'
    | '/services/local-seo-gujarat'
    | '/services/local-seo-hyderabad'
    | '/services/local-seo-jaipur'
    | '/services/local-seo-kolkata'
    | '/services/local-seo-lucknow'
    | '/services/local-seo-mumbai'
    | '/services/local-seo-pune'
    | '/services/local-seo-rajkot'
    | '/services/local-seo-surat'
    | '/services/local-seo-vadodara'
    | '/blog'
    | '/dashboard/magic-qr'
    | '/dashboard/posts'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/crm/leads'
    | '/crm/proposals'
    | '/crm/reports'
    | '/crm/settings'
    | '/crm/team'
    | '/api/public/leads'
    | '/dashboard'
    | '/crm'
    | '/crm/lead/$id'
    | '/api/public/cron/publish-due'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_crm'
    | '/auth'
    | '/bakery-marketing-software'
    | '/car-garage-marketing-software'
    | '/clinic-marketing-software'
    | '/contact'
    | '/demo'
    | '/education-marketing-software'
    | '/gym-marketing-software'
    | '/handyman-marketing-software'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-generate-magic-qr'
    | '/how-to-post-on-gbp'
    | '/how-to-reply-review'
    | '/login'
    | '/official-partner'
    | '/partner'
    | '/pest-control-marketing-software'
    | '/post-management'
    | '/pricing'
    | '/privacy-policy'
    | '/realestate-marketing-software'
    | '/restaurant-marketing-software'
    | '/salon-marketing-software'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/tour-travel-marketing-software'
    | '/yoga-wellness-marketing-software'
    | '/_authenticated/dashboard'
    | '/_crm/crm'
    | '/blog/$slug'
    | '/crm/login'
    | '/features/ai-post-generation'
    | '/features/magic-qr'
    | '/features/review-management'
    | '/features/smart-scheduling'
    | '/r/$slug'
    | '/services/local-seo'
    | '/services/local-seo-ahmedabad'
    | '/services/local-seo-bangalore'
    | '/services/local-seo-chennai'
    | '/services/local-seo-delhi'
    | '/services/local-seo-gujarat'
    | '/services/local-seo-hyderabad'
    | '/services/local-seo-jaipur'
    | '/services/local-seo-kolkata'
    | '/services/local-seo-lucknow'
    | '/services/local-seo-mumbai'
    | '/services/local-seo-pune'
    | '/services/local-seo-rajkot'
    | '/services/local-seo-surat'
    | '/services/local-seo-vadodara'
    | '/blog/'
    | '/_authenticated/dashboard/magic-qr'
    | '/_authenticated/dashboard/posts'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/settings'
    | '/_crm/crm/leads'
    | '/_crm/crm/proposals'
    | '/_crm/crm/reports'
    | '/_crm/crm/settings'
    | '/_crm/crm/team'
    | '/api/public/leads'
    | '/_authenticated/dashboard/'
    | '/_crm/crm/'
    | '/_crm/crm/lead/$id'
    | '/api/public/cron/publish-due'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CrmRoute: typeof CrmRouteWithChildren
  AuthRoute: typeof AuthRoute
  BakeryMarketingSoftwareRoute: typeof BakeryMarketingSoftwareRoute
  CarGarageMarketingSoftwareRoute: typeof CarGarageMarketingSoftwareRoute
  ClinicMarketingSoftwareRoute: typeof ClinicMarketingSoftwareRoute
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  EducationMarketingSoftwareRoute: typeof EducationMarketingSoftwareRoute
  GymMarketingSoftwareRoute: typeof GymMarketingSoftwareRoute
  HandymanMarketingSoftwareRoute: typeof HandymanMarketingSoftwareRoute
  HowToConnectGbpRoute: typeof HowToConnectGbpRoute
  HowToCreatePostRoute: typeof HowToCreatePostRoute
  HowToGenerateMagicQrRoute: typeof HowToGenerateMagicQrRoute
  HowToPostOnGbpRoute: typeof HowToPostOnGbpRoute
  HowToReplyReviewRoute: typeof HowToReplyReviewRoute
  LoginRoute: typeof LoginRoute
  OfficialPartnerRoute: typeof OfficialPartnerRoute
  PartnerRoute: typeof PartnerRoute
  PestControlMarketingSoftwareRoute: typeof PestControlMarketingSoftwareRoute
  PostManagementRoute: typeof PostManagementRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RealestateMarketingSoftwareRoute: typeof RealestateMarketingSoftwareRoute
  RestaurantMarketingSoftwareRoute: typeof RestaurantMarketingSoftwareRoute
  SalonMarketingSoftwareRoute: typeof SalonMarketingSoftwareRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TourTravelMarketingSoftwareRoute: typeof TourTravelMarketingSoftwareRoute
  YogaWellnessMarketingSoftwareRoute: typeof YogaWellnessMarketingSoftwareRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CrmLoginRoute: typeof CrmLoginRoute
  FeaturesAiPostGenerationRoute: typeof FeaturesAiPostGenerationRoute
  FeaturesMagicQrRoute: typeof FeaturesMagicQrRoute
  FeaturesReviewManagementRoute: typeof FeaturesReviewManagementRoute
  FeaturesSmartSchedulingRoute: typeof FeaturesSmartSchedulingRoute
  RSlugRoute: typeof RSlugRoute
  ServicesLocalSeoRoute: typeof ServicesLocalSeoRoute
  ServicesLocalSeoAhmedabadRoute: typeof ServicesLocalSeoAhmedabadRoute
  ServicesLocalSeoBangaloreRoute: typeof ServicesLocalSeoBangaloreRoute
  ServicesLocalSeoChennaiRoute: typeof ServicesLocalSeoChennaiRoute
  ServicesLocalSeoDelhiRoute: typeof ServicesLocalSeoDelhiRoute
  ServicesLocalSeoGujaratRoute: typeof ServicesLocalSeoGujaratRoute
  ServicesLocalSeoHyderabadRoute: typeof ServicesLocalSeoHyderabadRoute
  ServicesLocalSeoJaipurRoute: typeof ServicesLocalSeoJaipurRoute
  ServicesLocalSeoKolkataRoute: typeof ServicesLocalSeoKolkataRoute
  ServicesLocalSeoLucknowRoute: typeof ServicesLocalSeoLucknowRoute
  ServicesLocalSeoMumbaiRoute: typeof ServicesLocalSeoMumbaiRoute
  ServicesLocalSeoPuneRoute: typeof ServicesLocalSeoPuneRoute
  ServicesLocalSeoRajkotRoute: typeof ServicesLocalSeoRajkotRoute
  ServicesLocalSeoSuratRoute: typeof ServicesLocalSeoSuratRoute
  ServicesLocalSeoVadodaraRoute: typeof ServicesLocalSeoVadodaraRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicCronPublishDueRoute: typeof ApiPublicCronPublishDueRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_crm': {
      id: '/_crm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery-marketing-software': {
      id: '/bakery-marketing-software'
      path: '/bakery-marketing-software'
      fullPath: '/bakery-marketing-software'
      preLoaderRoute: typeof BakeryMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-garage-marketing-software': {
      id: '/car-garage-marketing-software'
      path: '/car-garage-marketing-software'
      fullPath: '/car-garage-marketing-software'
      preLoaderRoute: typeof CarGarageMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-marketing-software': {
      id: '/clinic-marketing-software'
      path: '/clinic-marketing-software'
      fullPath: '/clinic-marketing-software'
      preLoaderRoute: typeof ClinicMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education-marketing-software': {
      id: '/education-marketing-software'
      path: '/education-marketing-software'
      fullPath: '/education-marketing-software'
      preLoaderRoute: typeof EducationMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-marketing-software': {
      id: '/gym-marketing-software'
      path: '/gym-marketing-software'
      fullPath: '/gym-marketing-software'
      preLoaderRoute: typeof GymMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handyman-marketing-software': {
      id: '/handyman-marketing-software'
      path: '/handyman-marketing-software'
      fullPath: '/handyman-marketing-software'
      preLoaderRoute: typeof HandymanMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-connect-gbp': {
      id: '/how-to-connect-gbp'
      path: '/how-to-connect-gbp'
      fullPath: '/how-to-connect-gbp'
      preLoaderRoute: typeof HowToConnectGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-create-post': {
      id: '/how-to-create-post'
      path: '/how-to-create-post'
      fullPath: '/how-to-create-post'
      preLoaderRoute: typeof HowToCreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-generate-magic-qr': {
      id: '/how-to-generate-magic-qr'
      path: '/how-to-generate-magic-qr'
      fullPath: '/how-to-generate-magic-qr'
      preLoaderRoute: typeof HowToGenerateMagicQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-post-on-gbp': {
      id: '/how-to-post-on-gbp'
      path: '/how-to-post-on-gbp'
      fullPath: '/how-to-post-on-gbp'
      preLoaderRoute: typeof HowToPostOnGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-reply-review': {
      id: '/how-to-reply-review'
      path: '/how-to-reply-review'
      fullPath: '/how-to-reply-review'
      preLoaderRoute: typeof HowToReplyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official-partner': {
      id: '/official-partner'
      path: '/official-partner'
      fullPath: '/official-partner'
      preLoaderRoute: typeof OfficialPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pest-control-marketing-software': {
      id: '/pest-control-marketing-software'
      path: '/pest-control-marketing-software'
      fullPath: '/pest-control-marketing-software'
      preLoaderRoute: typeof PestControlMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-management': {
      id: '/post-management'
      path: '/post-management'
      fullPath: '/post-management'
      preLoaderRoute: typeof PostManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realestate-marketing-software': {
      id: '/realestate-marketing-software'
      path: '/realestate-marketing-software'
      fullPath: '/realestate-marketing-software'
      preLoaderRoute: typeof RealestateMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-marketing-software': {
      id: '/restaurant-marketing-software'
      path: '/restaurant-marketing-software'
      fullPath: '/restaurant-marketing-software'
      preLoaderRoute: typeof RestaurantMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-marketing-software': {
      id: '/salon-marketing-software'
      path: '/salon-marketing-software'
      fullPath: '/salon-marketing-software'
      preLoaderRoute: typeof SalonMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-travel-marketing-software': {
      id: '/tour-travel-marketing-software'
      path: '/tour-travel-marketing-software'
      fullPath: '/tour-travel-marketing-software'
      preLoaderRoute: typeof TourTravelMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga-wellness-marketing-software': {
      id: '/yoga-wellness-marketing-software'
      path: '/yoga-wellness-marketing-software'
      fullPath: '/yoga-wellness-marketing-software'
      preLoaderRoute: typeof YogaWellnessMarketingSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_crm/crm': {
      id: '/_crm/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmCrmRouteImport
      parentRoute: typeof CrmRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/login': {
      id: '/crm/login'
      path: '/crm/login'
      fullPath: '/crm/login'
      preLoaderRoute: typeof CrmLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/ai-post-generation': {
      id: '/features/ai-post-generation'
      path: '/features/ai-post-generation'
      fullPath: '/features/ai-post-generation'
      preLoaderRoute: typeof FeaturesAiPostGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/magic-qr': {
      id: '/features/magic-qr'
      path: '/features/magic-qr'
      fullPath: '/features/magic-qr'
      preLoaderRoute: typeof FeaturesMagicQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/review-management': {
      id: '/features/review-management'
      path: '/features/review-management'
      fullPath: '/features/review-management'
      preLoaderRoute: typeof FeaturesReviewManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/smart-scheduling': {
      id: '/features/smart-scheduling'
      path: '/features/smart-scheduling'
      fullPath: '/features/smart-scheduling'
      preLoaderRoute: typeof FeaturesSmartSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo': {
      id: '/services/local-seo'
      path: '/services/local-seo'
      fullPath: '/services/local-seo'
      preLoaderRoute: typeof ServicesLocalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-ahmedabad': {
      id: '/services/local-seo-ahmedabad'
      path: '/services/local-seo-ahmedabad'
      fullPath: '/services/local-seo-ahmedabad'
      preLoaderRoute: typeof ServicesLocalSeoAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-bangalore': {
      id: '/services/local-seo-bangalore'
      path: '/services/local-seo-bangalore'
      fullPath: '/services/local-seo-bangalore'
      preLoaderRoute: typeof ServicesLocalSeoBangaloreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-chennai': {
      id: '/services/local-seo-chennai'
      path: '/services/local-seo-chennai'
      fullPath: '/services/local-seo-chennai'
      preLoaderRoute: typeof ServicesLocalSeoChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-delhi': {
      id: '/services/local-seo-delhi'
      path: '/services/local-seo-delhi'
      fullPath: '/services/local-seo-delhi'
      preLoaderRoute: typeof ServicesLocalSeoDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-gujarat': {
      id: '/services/local-seo-gujarat'
      path: '/services/local-seo-gujarat'
      fullPath: '/services/local-seo-gujarat'
      preLoaderRoute: typeof ServicesLocalSeoGujaratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-hyderabad': {
      id: '/services/local-seo-hyderabad'
      path: '/services/local-seo-hyderabad'
      fullPath: '/services/local-seo-hyderabad'
      preLoaderRoute: typeof ServicesLocalSeoHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-jaipur': {
      id: '/services/local-seo-jaipur'
      path: '/services/local-seo-jaipur'
      fullPath: '/services/local-seo-jaipur'
      preLoaderRoute: typeof ServicesLocalSeoJaipurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-kolkata': {
      id: '/services/local-seo-kolkata'
      path: '/services/local-seo-kolkata'
      fullPath: '/services/local-seo-kolkata'
      preLoaderRoute: typeof ServicesLocalSeoKolkataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-lucknow': {
      id: '/services/local-seo-lucknow'
      path: '/services/local-seo-lucknow'
      fullPath: '/services/local-seo-lucknow'
      preLoaderRoute: typeof ServicesLocalSeoLucknowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-mumbai': {
      id: '/services/local-seo-mumbai'
      path: '/services/local-seo-mumbai'
      fullPath: '/services/local-seo-mumbai'
      preLoaderRoute: typeof ServicesLocalSeoMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-pune': {
      id: '/services/local-seo-pune'
      path: '/services/local-seo-pune'
      fullPath: '/services/local-seo-pune'
      preLoaderRoute: typeof ServicesLocalSeoPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-rajkot': {
      id: '/services/local-seo-rajkot'
      path: '/services/local-seo-rajkot'
      fullPath: '/services/local-seo-rajkot'
      preLoaderRoute: typeof ServicesLocalSeoRajkotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-surat': {
      id: '/services/local-seo-surat'
      path: '/services/local-seo-surat'
      fullPath: '/services/local-seo-surat'
      preLoaderRoute: typeof ServicesLocalSeoSuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/local-seo-vadodara': {
      id: '/services/local-seo-vadodara'
      path: '/services/local-seo-vadodara'
      fullPath: '/services/local-seo-vadodara'
      preLoaderRoute: typeof ServicesLocalSeoVadodaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/magic-qr': {
      id: '/_authenticated/dashboard/magic-qr'
      path: '/magic-qr'
      fullPath: '/dashboard/magic-qr'
      preLoaderRoute: typeof AuthenticatedDashboardMagicQrRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/posts': {
      id: '/_authenticated/dashboard/posts'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof AuthenticatedDashboardPostsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_crm/crm/': {
      id: '/_crm/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmCrmIndexRouteImport
      parentRoute: typeof CrmCrmRoute
    }
    '/_crm/crm/leads': {
      id: '/_crm/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmCrmLeadsRouteImport
      parentRoute: typeof CrmCrmRoute
    }
    '/_crm/crm/proposals': {
      id: '/_crm/crm/proposals'
      path: '/proposals'
      fullPath: '/crm/proposals'
      preLoaderRoute: typeof CrmCrmProposalsRouteImport
      parentRoute: typeof CrmCrmRoute
    }
    '/_crm/crm/reports': {
      id: '/_crm/crm/reports'
      path: '/reports'
      fullPath: '/crm/reports'
      preLoaderRoute: typeof CrmCrmReportsRouteImport
      parentRoute: typeof CrmCrmRoute
    }
    '/_crm/crm/settings': {
      id: '/_crm/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof CrmCrmSettingsRouteImport
      parentRoute: typeof CrmCrmRoute
    }
    '/_crm/crm/team': {
      id: '/_crm/crm/team'
      path: '/team'
      fullPath: '/crm/team'
      preLoaderRoute: typeof CrmCrmTeamRouteImport
      parentRoute: typeof CrmCrmRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_crm/crm/lead/$id': {
      id: '/_crm/crm/lead/$id'
      path: '/lead/$id'
      fullPath: '/crm/lead/$id'
      preLoaderRoute: typeof CrmCrmLeadIdRouteImport
      parentRoute: typeof CrmCrmRoute
    }
    '/api/public/cron/publish-due': {
      id: '/api/public/cron/publish-due'
      path: '/api/public/cron/publish-due'
      fullPath: '/api/public/cron/publish-due'
      preLoaderRoute: typeof ApiPublicCronPublishDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardMagicQrRoute: typeof AuthenticatedDashboardMagicQrRoute
  AuthenticatedDashboardPostsRoute: typeof AuthenticatedDashboardPostsRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardMagicQrRoute: AuthenticatedDashboardMagicQrRoute,
    AuthenticatedDashboardPostsRoute: AuthenticatedDashboardPostsRoute,
    AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CrmCrmRouteChildren {
  CrmCrmLeadsRoute: typeof CrmCrmLeadsRoute
  CrmCrmProposalsRoute: typeof CrmCrmProposalsRoute
  CrmCrmReportsRoute: typeof CrmCrmReportsRoute
  CrmCrmSettingsRoute: typeof CrmCrmSettingsRoute
  CrmCrmTeamRoute: typeof CrmCrmTeamRoute
  CrmCrmIndexRoute: typeof CrmCrmIndexRoute
  CrmCrmLeadIdRoute: typeof CrmCrmLeadIdRoute
}

const CrmCrmRouteChildren: CrmCrmRouteChildren = {
  CrmCrmLeadsRoute: CrmCrmLeadsRoute,
  CrmCrmProposalsRoute: CrmCrmProposalsRoute,
  CrmCrmReportsRoute: CrmCrmReportsRoute,
  CrmCrmSettingsRoute: CrmCrmSettingsRoute,
  CrmCrmTeamRoute: CrmCrmTeamRoute,
  CrmCrmIndexRoute: CrmCrmIndexRoute,
  CrmCrmLeadIdRoute: CrmCrmLeadIdRoute,
}

const CrmCrmRouteWithChildren =
  CrmCrmRoute._addFileChildren(CrmCrmRouteChildren)

interface CrmRouteChildren {
  CrmCrmRoute: typeof CrmCrmRouteWithChildren
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmCrmRoute: CrmCrmRouteWithChildren,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CrmRoute: CrmRouteWithChildren,
  AuthRoute: AuthRoute,
  BakeryMarketingSoftwareRoute: BakeryMarketingSoftwareRoute,
  CarGarageMarketingSoftwareRoute: CarGarageMarketingSoftwareRoute,
  ClinicMarketingSoftwareRoute: ClinicMarketingSoftwareRoute,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  EducationMarketingSoftwareRoute: EducationMarketingSoftwareRoute,
  GymMarketingSoftwareRoute: GymMarketingSoftwareRoute,
  HandymanMarketingSoftwareRoute: HandymanMarketingSoftwareRoute,
  HowToConnectGbpRoute: HowToConnectGbpRoute,
  HowToCreatePostRoute: HowToCreatePostRoute,
  HowToGenerateMagicQrRoute: HowToGenerateMagicQrRoute,
  HowToPostOnGbpRoute: HowToPostOnGbpRoute,
  HowToReplyReviewRoute: HowToReplyReviewRoute,
  LoginRoute: LoginRoute,
  OfficialPartnerRoute: OfficialPartnerRoute,
  PartnerRoute: PartnerRoute,
  PestControlMarketingSoftwareRoute: PestControlMarketingSoftwareRoute,
  PostManagementRoute: PostManagementRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RealestateMarketingSoftwareRoute: RealestateMarketingSoftwareRoute,
  RestaurantMarketingSoftwareRoute: RestaurantMarketingSoftwareRoute,
  SalonMarketingSoftwareRoute: SalonMarketingSoftwareRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TourTravelMarketingSoftwareRoute: TourTravelMarketingSoftwareRoute,
  YogaWellnessMarketingSoftwareRoute: YogaWellnessMarketingSoftwareRoute,
  BlogSlugRoute: BlogSlugRoute,
  CrmLoginRoute: CrmLoginRoute,
  FeaturesAiPostGenerationRoute: FeaturesAiPostGenerationRoute,
  FeaturesMagicQrRoute: FeaturesMagicQrRoute,
  FeaturesReviewManagementRoute: FeaturesReviewManagementRoute,
  FeaturesSmartSchedulingRoute: FeaturesSmartSchedulingRoute,
  RSlugRoute: RSlugRoute,
  ServicesLocalSeoRoute: ServicesLocalSeoRoute,
  ServicesLocalSeoAhmedabadRoute: ServicesLocalSeoAhmedabadRoute,
  ServicesLocalSeoBangaloreRoute: ServicesLocalSeoBangaloreRoute,
  ServicesLocalSeoChennaiRoute: ServicesLocalSeoChennaiRoute,
  ServicesLocalSeoDelhiRoute: ServicesLocalSeoDelhiRoute,
  ServicesLocalSeoGujaratRoute: ServicesLocalSeoGujaratRoute,
  ServicesLocalSeoHyderabadRoute: ServicesLocalSeoHyderabadRoute,
  ServicesLocalSeoJaipurRoute: ServicesLocalSeoJaipurRoute,
  ServicesLocalSeoKolkataRoute: ServicesLocalSeoKolkataRoute,
  ServicesLocalSeoLucknowRoute: ServicesLocalSeoLucknowRoute,
  ServicesLocalSeoMumbaiRoute: ServicesLocalSeoMumbaiRoute,
  ServicesLocalSeoPuneRoute: ServicesLocalSeoPuneRoute,
  ServicesLocalSeoRajkotRoute: ServicesLocalSeoRajkotRoute,
  ServicesLocalSeoSuratRoute: ServicesLocalSeoSuratRoute,
  ServicesLocalSeoVadodaraRoute: ServicesLocalSeoVadodaraRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicCronPublishDueRoute: ApiPublicCronPublishDueRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
