/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HowToConnectGbpRouteImport } from './routes/how-to-connect-gbp'
import { Route as HowToCreatePostRouteImport } from './routes/how-to-create-post'
import { Route as HowToReplyReviewRouteImport } from './routes/how-to-reply-review'
import { Route as LoginRouteImport } from './routes/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToConnectGbpRoute = HowToConnectGbpRouteImport.update({
  id: '/how-to-connect-gbp',
  path: '/how-to-connect-gbp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToCreatePostRoute = HowToCreatePostRouteImport.update({
  id: '/how-to-create-post',
  path: '/how-to-create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToReplyReviewRoute = HowToReplyReviewRouteImport.update({
  id: '/how-to-reply-review',
  path: '/how-to-reply-review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/how-to-connect-gbp': typeof HowToConnectGbpRoute
  '/how-to-create-post': typeof HowToCreatePostRoute
  '/how-to-reply-review': typeof HowToReplyReviewRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-reply-review'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-reply-review'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/how-to-connect-gbp'
    | '/how-to-create-post'
    | '/how-to-reply-review'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  HowToConnectGbpRoute: typeof HowToConnectGbpRoute
  HowToCreatePostRoute: typeof HowToCreatePostRoute
  HowToReplyReviewRoute: typeof HowToReplyReviewRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-connect-gbp': {
      id: '/how-to-connect-gbp'
      path: '/how-to-connect-gbp'
      fullPath: '/how-to-connect-gbp'
      preLoaderRoute: typeof HowToConnectGbpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-create-post': {
      id: '/how-to-create-post'
      path: '/how-to-create-post'
      fullPath: '/how-to-create-post'
      preLoaderRoute: typeof HowToCreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-reply-review': {
      id: '/how-to-reply-review'
      path: '/how-to-reply-review'
      fullPath: '/how-to-reply-review'
      preLoaderRoute: typeof HowToReplyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  HowToConnectGbpRoute: HowToConnectGbpRoute,
  HowToCreatePostRoute: HowToCreatePostRoute,
  HowToReplyReviewRoute: HowToReplyReviewRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
